const TransactionJson = {
    "transactions": [
        {
            "id": "TRANS1",
            "orderId":"HSHSJH67676",
            "invoiceId":"#DDEE33",
            "total": 2328,
            "userId": 97,
            "transactionDate": "20/10/2022",
            "paymentMethod": 1,            
            "status": 4,
        },
        {
            "id": "TRANS2",
            "orderId":"HSHSJH67676",
            "invoiceId":"#DDEE33",
            "total": 2328,
            "userId": 97,
            "transactionDate": "20/10/2022",
            "paymentMethod": 2,            
            "status": 3,
        },
        {
            "id": "TRANS3",
            "orderId":"HSHSJH67676",
            "invoiceId":"#DDEE33",
            "total": 2328,
            "userId": 97,
            "transactionDate": "20/10/2022",
            "paymentMethod": 3,            
            "status": 1,
        },
        {
            "id": "TRANS4",
            "orderId":"HSHSJH67676",
            "invoiceId":"#DDEE33",
            "total": 2328,
            "userId": 97,
            "transactionDate": "20/10/2022",
            "paymentMethod": 4,            
            "status": 2,
        },
        {
            "id": "TRANS5",
            "orderId":"HSHSJH67676",
            "invoiceId":"#DDEE33",
            "total": 2328,
            "userId": 97,
            "transactionDate": "20/10/2022",
            "paymentMethod": 5,            
            "status": 4,
        },
        {
            "id": "TRANS6",
            "orderId":"HSHSJH67676",
            "invoiceId":"#DDEE33",
            "total": 2328,
            "userId": 97,
            "transactionDate": "20/10/2022",
            "paymentMethod": 1,            
            "status": 3,
        },
        {
            "id": "TRANS7",
            "orderId":"HSHSJH67676",
            "invoiceId":"#DDEE33",
            "total": 2328,
            "userId": 97,
            "transactionDate": "20/10/2022",
            "paymentMethod": 1,            
            "status": 1,
        },
        {
            "id": "TRANS8",
            "orderId":"HSHSJH67676",
            "invoiceId":"#DDEE33",
            "total": 2328,
            "userId": 97,
            "transactionDate": "20/10/2022",
            "paymentMethod": 1,            
            "status": 2,
        },
        {
            "id": "TRANS9",
            "orderId":"HSHSJH67676",
            "invoiceId":"#DDEE33",
            "total": 2328,
            "userId": 97,
            "transactionDate": "20/10/2022",
            "paymentMethod": 1,            
            "status": 4,
        },
        {
            "id": "TRANS10",
            "orderId":"HSHSJH67676",
            "invoiceId":"#DDEE33",
            "total": 2328,
            "userId": 97,
            "transactionDate": "20/10/2022",
            "paymentMethod": 1,            
            "status": 3,
        },
        {
            "id": "TRANS11",
            "orderId":"HSHSJH67676",
            "invoiceId":"#DDEE33",
            "total": 2328,
            "userId": 97,
            "transactionDate": "20/10/2022",
            "paymentMethod": 1,            
            "status": 1,
        },
        {
            "id": "TRANS12",
            "orderId":"HSHSJH67676",
            "invoiceId":"#DDEE33",
            "total": 2328,
            "userId": 97,
            "transactionDate": "20/10/2022",
            "paymentMethod": 1,            
            "status": 2,
        },
    ],
    "total": 20,
    "skip": 0,
    "limit": 20
}
export default TransactionJson;